version: '3.1'

services:

  database-importacao:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: importacao_distribuida
      MYSQL_USER: importacao_distribuida
      MYSQL_PASSWORD: importacao_distribuida
    ports:
      - 3306:3306
    networks:
      - importacao-distribuida

  database-crm:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
      MYSQL_USER: crm
      MYSQL_PASSWORD: crm
    ports:
      - 3307:3306
    volumes:
      - "./scripts/crm_database_init.sql:/docker-entrypoint-initdb.d/crm_database_init.sql"
    networks:
      - importacao-distribuida

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - importacao-distribuida

  rabbitmq:
    image: "rabbitmq:management-alpine"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - importacao-distribuida


networks:
  importacao-distribuida: